### ISSUE TITLE
We need more content!

### ISSUE THREAD

**Issue by beastmode2306** [Ders1k/ComputerPeripheralsBackend#2]
Where are new updates?
We need new features so bad!
Why this developer is throwing this gem project? :(

**Comment by nottoday2471** [comment]
Hello,

I would like to request a new feature for your Node.js NestJS peripherals shop. As a customer, I would find it very useful if the shop had a "compare" feature that allowed me to easily compare different products side by side.

For example, when browsing for a new computer mouse, I might want to compare the DPI, weight, and price of several different models. If there was a "compare" button next to each product, I could select multiple products and see their features in a table or chart format. This would save me time and help me make an informed decision about which product to purchase.

I think this feature would be valuable for many customers, especially those who are looking to make a more complex purchase or want to compare products from different brands. Please let me know if this feature is something your team would consider implementing in the future.

Thank you for your time and consideration.

**Comment by dovgopoly** [comment]
Agree! Dude, we need more stuff to review
